# Generated by Django 3.1.2 on 2020-10-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_car_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='oil_service',
        ),
        migrations.AddField(
            model_name='car',
            name='oil_service_date_last_done',
            field=models.DateField(default='2020-09-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='oil_service_interval',
            field=models.PositiveSmallIntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='oil_service_mileage_last_done',
            field=models.PositiveIntegerField(default=333333),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='oil_service_oil_type',
            field=models.CharField(default='10w-40', max_length=128),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OilService',
        ),
    ]
